export interface Book {
	position: string,
	slug: string;
	label: string;
	chapters: number;
}

export const books: Array<Book> = [
	{ slug: 'sa', label: 'Sáng-thế Ký', chapters: 50, position: '01' },
	{
		slug: 'xu',
		label: 'Xuất Ê-díp-tô Ký', chapters: 40,
		position: '02',
	},
	{ slug: 'le', label: 'Lê-vi Ký', chapters: 27, position: '03' },
	{ slug: 'dan', label: 'Dân-số Ký', chapters: 36, position: '04' },
	{
		slug: 'phu',
		label: 'Phục-truyền Luật-lệ Ký',
		chapters: 34,
		position: '05',
	},
	{ slug: 'gios', label: 'Giô-suê', chapters: 24, position: '06' },
	{ slug: 'cac', label: 'Các Quan Xét', chapters: 21, position: '07' },
	{ slug: 'ru', label: 'Ru-tơ', chapters: 4, position: '08' },
	{ slug: '1sa', label: 'I Sa-mu-ên', chapters: 31, position: '09' },
	{ slug: '2sa', label: 'II Sa-mu-ên', chapters: 24, position: '10' },
	{ slug: '1vua', label: 'I Các Vua', chapters: 22, position: '11' },
	{ slug: '2vua', label: 'II Các Vua', chapters: 25, position: '12' },
	{ slug: '1su', label: 'I Sử-ký', chapters: 29, position: '13' },
	{ slug: '2su', label: 'II Sử-ký', chapters: 36, position: '14' },
	{ slug: 'exo', label: 'E-xơ-ra', chapters: 10, position: '15' },
	{ slug: 'ne', label: 'Nê-hê-mi', chapters: 13, position: '16' },
	{ slug: 'et', label: 'Ê-xơ-tê', chapters: 10, position: '17' },
	{ slug: 'giop', label: 'Gióp', chapters: 42, position: '18' },
	{ slug: 'thi', label: 'Thi-thiên', chapters: 150, position: '19' },
	{ slug: 'ch', label: 'Châm-ngôn', chapters: 31, position: '20' },
	{ slug: 'tr', label: 'Truyền-đạo', chapters: 12, position: '21' },
	{ slug: 'nha', label: 'Nhã-ca', chapters: 8, position: '22' },
	{ slug: 'es', label: 'Ê-sai', chapters: 66, position: '23' },
	{ slug: 'gie', label: 'Giê-rê-mi', chapters: 52, position: '24' },
	{ slug: 'ca', label: 'Ca-thương', chapters: 5, position: '25' },
	{ slug: 'exe', label: 'Ê-xê-chi-ên', chapters: 48, position: '26' },
	{ slug: 'da', label: 'Đa-ni-ên', chapters: 12, position: '27' },
	{ slug: 'os', label: 'Ô-sê', chapters: 14, position: '28' },
	{ slug: 'gio', label: 'Giô-ên', chapters: 3, position: '29' },
	{ slug: 'am', label: 'A-mốt', chapters: 9, position: '30' },
	{ slug: 'ap', label: 'Áp-đia', chapters: 1, position: '31' },
	{ slug: 'gion', label: 'Giô-na', chapters: 4, position: '32' },
	{ slug: 'mi', label: 'Mi-chê', chapters: 7, position: '33' },
	{ slug: 'na', label: 'Na-hum', chapters: 3, position: '34' },
	{ slug: 'ha', label: 'Ha-ba-cúc', chapters: 3, position: '35' },
	{ slug: 'so', label: 'Sô-phô-ni', chapters: 3, position: '36' },
	{ slug: 'ag', label: 'A-ghê', chapters: 2, position: '37' },
	{ slug: 'xa', label: 'Xa-cha-ri', chapters: 14, position: '38' },
	{ slug: 'ma', label: 'Ma-la-chi', chapters: 4, position: '39' },
	{ slug: 'mat', label: 'Ma-thi-ơ', chapters: 28, position: '40' },
	{ slug: 'mac', label: 'Mác', chapters: 16, position: '41' },
	{ slug: 'lu', label: 'Lu-ca', chapters: 24, position: '42' },
	{ slug: 'gi', label: 'Giăng', chapters: 21, position: '43' },
	{
		slug: 'cong',
		label: 'Công-vụ các Sứ-đồ',
		chapters: 28,
		position: '44',
	},
	{ slug: 'ro', label: 'Rô-ma', chapters: 16, position: '45' },
	{ slug: '1co', label: 'I Cô-rinh-tô', chapters: 16, position: '46' },
	{ slug: '2co', label: 'II Cô-rinh-tô', chapters: 13, position: '47' },
	{ slug: 'ga', label: 'Ga-la-ti', chapters: 6, position: '48' },
	{ slug: 'eph', label: 'Ê-phê-sô', chapters: 6, position: '49' },
	{ slug: 'phi', label: 'Phi-líp', chapters: 4, position: '50' },
	{ slug: 'co', label: 'Cô-lô-se', chapters: 4, position: '51' },
	{
		slug: '1te',
		label: 'I Tê-sa-lô-ni-ca',
		chapters: 5,
		position: '52',
	},
	{
		slug: '2te',
		label: 'II Tê-sa-lô-ni-ca',
		chapters: 3,
		position: '53',
	},
	{ slug: '1ti', label: 'I Ti-mô-thê', chapters: 6, position: '54' },
	{ slug: '2ti', label: 'II Ti-mô-thê', chapters: 4, position: '55' },
	{ slug: 'tit', label: 'Tít', chapters: 3, position: '56' },
	{ slug: 'phil', label: 'Phi-lê-môn', chapters: 1, position: '57' },
	{ slug: 'he', label: 'Hê-bơ-rơ', chapters: 13, position: '58' },
	{ slug: 'gia', label: 'Gia-cơ', chapters: 5, position: '59' },
	{ slug: '1phi', label: 'I Phi-e-rơ', chapters: 5, position: '60' },
	{ slug: '2phi', label: 'II Phi-e-rơ', chapters: 3, position: '61' },
	{ slug: '1gi', label: 'I Giăng', chapters: 5, position: '62' },
	{ slug: '2gi', label: 'II Giăng', chapters: 1, position: '63' },
	{ slug: '3gi', label: 'III Giăng', chapters: 1, position: '64' },
	{ slug: 'giu', label: 'Giu-đe', chapters: 1, position: '65' },
	{ slug: 'kh', label: 'Khải-huyền', chapters: 22, position: '66' },
];
