import { BookInfo, Language } from "./entities";

const codes = new Map<number, string>([
    [1, "SA"],
    [2, "XU"],
    [3, "LE"],
    [4, "DAN"],
    [5, "PHU"],
    [6, "GIOS"],
    [7, "CAC"],
    [8, "RU"],
    [9, "1SA"],
    [10, "2SA"],
    [11, "1VUA"],
    [12, "2VUA"],
    [13, "1SU"],
    [14, "2SU"],
    [15, "EXO"],
    [16, "NE"],
    [17, "ET"],
    [18, "GIOP"],
    [19, "THI"],
    [20, "CH"],
    [21, "TR"],
    [22, "NHA"],
    [23, "ES"],
    [24, "GIE"],
    [25, "CA"],
    [26, "EXE"],
    [27, "DA"],
    [28, "OS"],
    [29, "GIO"],
    [30, "AM"],
    [31, "AP"],
    [32, "GION"],
    [33, "MI"],
    [34, "NA"],
    [35, "HA"],
    [36, "SO"],
    [37, "AG"],
    [38, "XA"],
    [39, "MA"],
    [40, "MAT"],
    [41, "MAC"],
    [42, "LU"],
    [43, "GI"],
    [44, "CONG"],
    [45, "RO"],
    [46, "1CO"],
    [47, "2CO"],
    [48, "GA"],
    [49, "EPH"],
    [50, "PHI"],
    [51, "CO"],
    [52, "1TE"],
    [53, "2TE"],
    [54, "1TI"],
    [55, "2TI"],
    [56, "TIT"],
    [57, "PHIL"],
    [58, "HE"],
    [59, "GIA"],
    [60, "1PHI"],
    [61, "2PHI"],
    [62, "1GI"],
    [63, "2GI"],
    [64, "3GI"],
    [65, "GIU"],
    [66, "KH"],
]);

const chapters = new Map<number, number>([
    [1, 50],
    [2, 40],
    [3, 27],
    [4, 36],
    [5, 34],
    [6, 24],
    [7, 21],
    [8, 4],
    [9, 31],
    [10, 24],
    [11, 22],
    [12, 25],
    [13, 29],
    [14, 36],
    [15, 10],
    [16, 13],
    [17, 10],
    [18, 42],
    [19, 150],
    [20, 31],
    [21, 12],
    [22, 8],
    [23, 66],
    [24, 52],
    [25, 5],
    [26, 48],
    [27, 12],
    [28, 14],
    [29, 3],
    [30, 9],
    [31, 1],
    [32, 4],
    [33, 7],
    [34, 3],
    [35, 3],
    [36, 3],
    [37, 2],
    [38, 14],
    [39, 4],
    [40, 28],
    [41, 16],
    [42, 24],
    [43, 21],
    [44, 28],
    [45, 16],
    [46, 16],
    [47, 13],
    [48, 6],
    [49, 6],
    [50, 4],
    [51, 4],
    [52, 5],
    [53, 3],
    [54, 6],
    [55, 4],
    [56, 3],
    [57, 1],
    [58, 13],
    [59, 5],
    [60, 5],
    [61, 3],
    [62, 5],
    [63, 1],
    [64, 1],
    [65, 1],
    [66, 22],
]);

const viDict = new Map<string, string>([
    ["SA", "Sáng-thế Ký"],
    ["XU", "Xuất Ê-díp-tô Ký"],
    ["LE", "Lê-vi Ký"],
    ["DAN", "Dân-số Ký"],
    ["PHU", "Phục-truyền Luật-lệ Ký"],
    ["GIOS", "Giô-suê"],
    ["CAC", "Các Quan Xét"],
    ["RU", "Ru-tơ"],
    ["1SA", "I Sa-mu-ên"],
    ["2SA", "II Sa-mu-ên"],
    ["1VUA", "I Các Vua"],
    ["2VUA", "II Các Vua"],
    ["1SU", "I Sử-ký"],
    ["2SU", "II Sử-ký"],
    ["EXO", "E-xơ-ra"],
    ["NE", "Nê-hê-mi"],
    ["ET", "Ê-xơ-tê"],
    ["GIOP", "Gióp"],
    ["THI", "Thi Thiên"],
    ["CH", "Châm Ngôn"],
    ["TR", "Truyền Đạo"],
    ["NHA", "Nhã Ca"],
    ["ES", "Ê-sai"],
    ["GIE", "Giê-rê-mi"],
    ["CA", "Ca Thương"],
    ["EXE", "Ê-xê-chi-ên"],
    ["DA", "Đa-ni-ên"],
    ["OS", "Ô-sê"],
    ["GIO", "Giô-ên"],
    ["AM", "A-mốt"],
    ["AP", "Áp-đia"],
    ["GION", "Giô-na"],
    ["MI", "Mi-chê"],
    ["NA", "Na-hum"],
    ["HA", "Ha-ba-cúc"],
    ["SO", "Sô-phô-ni"],
    ["AG", "A-ghê"],
    ["XA", "Xa-cha-ri"],
    ["MA", "Ma-la-chi"],
    ["MAT", "Ma-thi-ơ"],
    ["MAC", "Mác"],
    ["LU", "Lu-ca"],
    ["GI", "Giăng"],
    ["CONG", "Công vụ các Sứ-đồ"],
    ["RO", "Rô-ma"],
    ["1CO", "I Cô-rinh-tô"],
    ["2CO", "II Cô-rinh-tô"],
    ["GA", "Ga-la-ti"],
    ["EPH", "Ê-phê-sô"],
    ["PHI", "Phi-líp"],
    ["CO", "Cô-lô-se"],
    ["1TE", "I Tê-sa-lô-ni-ca"],
    ["2TE", "II Tê-sa-lô-ni-ca"],
    ["1TI", "I Ti-mô-thê"],
    ["2TI", "II Ti-mô-thê"],
    ["TIT", "Tít"],
    ["PHIL", "Phi-lê-môn"],
    ["HE", "Hê-bơ-rơ"],
    ["GIA", "Gia-cơ"],
    ["1PHI", "I Phi-e-rơ"],
    ["2PHI", "II Phi-e-rơ"],
    ["1GI", "I Giăng"],
    ["2GI", "II Giăng"],
    ["3GI", "III Giăng"],
    ["GIU", "Giu-đe"],
    ["KH", "Khải Huyền"],
]);

const enDict = new Map<string, string>([
    ["sa", "Genesis"],
    ["xu", "Exodus"],
    ["le", "Leviticus"],
    ["dan", "Numbers"],
    ["phu", "Deuteronomy"],
    ["gios", "Joshua"],
    ["cac", "Judges"],
    ["ru", "Ruth"],
    ["1sa", "I"],
    ["2sa", "II"],
    ["1vua", "I"],
    ["2vua", "II"],
    ["1su", "I"],
    ["2su", "II"],
    ["exo", "Ezra"],
    ["ne", "Nehemial"],
    ["et", "Esther"],
    ["giop", "Job"],
    ["thi", "Psalms"],
    ["ch", "Proverbs"],
    ["tr", "Ecclesiastes"],
    ["nha", "Song"],
    ["es", "Isaiah"],
    ["gie", "Jeremiah"],
    ["ca", "Lamentations"],
    ["exe", "Ezekiel"],
    ["da", "Daniel"],
    ["os", "Hosea"],
    ["gio", "Joel"],
    ["am", "Amos"],
    ["ap", "Obadiah"],
    ["gion", "Jonah"],
    ["mi", "Micah"],
    ["na", "Nahum"],
    ["ha", "Habakkuk"],
    ["so", "Zephaniah"],
    ["ag", "Haggai"],
    ["xa", "Zechariah"],
    ["ma", "Malachi"],
    ["mat", "Matthew"],
    ["mac", "Mark"],
    ["lu", "Luke"],
    ["gi", "John"],
    ["cong", "Acts"],
    ["ro", "Roman"],
    ["1co", "I"],
    ["2co", "II"],
    ["ga", "Galatians"],
    ["eph", "Ephesians"],
    ["phi", "Philippians"],
    ["co", "Colossians"],
    ["1te", "I"],
    ["2te", "II"],
    ["1ti", "I"],
    ["2ti", "II"],
    ["tit", "Titus"],
    ["phil", "Philemon"],
    ["he", "Hebrews"],
    ["gia", "James"],
    ["1phi", "I"],
    ["2phi", "II"],
    ["1gi", "I"],
    ["2gi", "II"],
    ["3gi", "III"],
    ["giu", "Jude"],
    ["kh", "Revelation"],
]);

export const books = (
    () => {
        const items: Map<number, BookInfo> = new Map<number, BookInfo>();
        
        codes.forEach((code, pos) => {
            items.set(pos, {
                    code,
                    chapters: chapters.get(pos)!,
                    name: new Map<Language, string>([
                        [Language.VI, viDict.get(code)!],
                        [Language.EN, enDict.get(code)!],
                    ]),
                } as BookInfo,
            );
        });
        
        return items;
    }
)();
