export interface AudioState {
	text: string,
	url: string,
	pip: boolean,
	playing: boolean,
	controls: boolean,
	light: boolean,
	volume: number,
	muted: boolean,
	played: number,
	loaded: number,
	duration: number,
	playbackRate: number,
	loop: boolean,
	seeking: boolean,
	verbose: boolean,
	counter: number,
}

export const defaultAudioState: AudioState = {
	url: '',
	text: '',
	pip: false,
	playing: false,
	controls: false,
	light: false,
	volume: 0.8,
	muted: false,
	played: 0,
	loaded: 0,
	duration: 0,
	playbackRate: 1.0,
	loop: false,
	seeking: false,
	verbose: false,
	counter: 0,
};
