// https://stream.biblegateway.com/bibles/32/nkjv-bubb/John.1.adcb7d6af78e2e81fb68b3b27a9f3509.mp3

export interface Book {
	slug: string;
	label: string;
	chapters: number;
}

export const books: Array<Book> = [
	{ slug: 'sa', label: 'Sáng-thế Ký', chapters: 50 },
	{ slug: 'xu', label: 'Xuất Ê-díp-tô Ký', chapters: 40 },
	{ slug: 'le', label: 'Lê-vi Ký', chapters: 27 },
	{ slug: 'dan', label: 'Dân-số Ký', chapters: 36 },
	{ slug: 'phu', label: 'Phục-truyền Luật-lệ Ký', chapters: 34 },
	{ slug: 'gios', label: 'Giô-suê', chapters: 24 },
	{ slug: 'cac', label: 'Các Quan Xét', chapters: 21 },
	{ slug: 'ru', label: 'Ru-tơ', chapters: 4 },
	{ slug: '1sa', label: 'I Sa-mu-ên', chapters: 31 },
	{ slug: '2sa', label: 'II Sa-mu-ên', chapters: 24 },
	{ slug: '1vua', label: 'I Các Vua', chapters: 22 },
	{ slug: '2vua', label: 'II Các Vua', chapters: 25 },
	{ slug: '1su', label: 'I Sử-ký', chapters: 29 },
	{ slug: '2su', label: 'II Sử-ký', chapters: 36 },
	{ slug: 'exo', label: 'E-xơ-ra', chapters: 10 },
	{ slug: 'ne', label: 'Nê-hê-mi', chapters: 13 },
	{ slug: 'et', label: 'Ê-xơ-tê', chapters: 10 },
	{ slug: 'giop', label: 'Gióp', chapters: 42 },
	{ slug: 'thi', label: 'Thi-thiên', chapters: 150 },
	{ slug: 'ch', label: 'Châm-ngôn', chapters: 31 },
	{ slug: 'tr', label: 'Truyền-đạo', chapters: 12 },
	{ slug: 'nha', label: 'Nhã-ca', chapters: 8 },
	{ slug: 'es', label: 'Ê-sai', chapters: 66 },
	{ slug: 'gie', label: 'Giê-rê-mi', chapters: 52 },
	{ slug: 'ca', label: 'Ca-thương', chapters: 5 },
	{ slug: 'exe', label: 'Ê-xê-chi-ên', chapters: 48 },
	{ slug: 'da', label: 'Đa-ni-ên', chapters: 12 },
	{ slug: 'os', label: 'Ô-sê', chapters: 14 },
	{ slug: 'gio', label: 'Giô-ên', chapters: 3 },
	{ slug: 'am', label: 'A-mốt', chapters: 9 },
	{ slug: 'ap', label: 'Áp-đia', chapters: 1 },
	{ slug: 'gion', label: 'Giô-na', chapters: 4 },
	{ slug: 'mi', label: 'Mi-chê', chapters: 7 },
	{ slug: 'na', label: 'Na-hum', chapters: 3 },
	{ slug: 'ha', label: 'Ha-ba-cúc', chapters: 3 },
	{ slug: 'so', label: 'Sô-phô-ni', chapters: 3 },
	{ slug: 'ag', label: 'A-ghê', chapters: 2 },
	{ slug: 'xa', label: 'Xa-cha-ri', chapters: 14 },
	{ slug: 'ma', label: 'Ma-la-chi', chapters: 4 },
	{ slug: 'mat', label: 'Ma-thi-ơ', chapters: 28 },
	{ slug: 'mac', label: 'Mác', chapters: 16 },
	{ slug: 'lu', label: 'Lu-ca', chapters: 24 },
	{ slug: 'gi', label: 'Giăng', chapters: 21 },
	{ slug: 'cong', label: 'Công-vụ các Sứ-đồ', chapters: 28 },
	{ slug: 'ro', label: 'Rô-ma', chapters: 16 },
	{ slug: '1co', label: 'I Cô-rinh-tô', chapters: 16 },
	{ slug: '2co', label: 'II Cô-rinh-tô', chapters: 13 },
	{ slug: 'ga', label: 'Ga-la-ti', chapters: 6 },
	{ slug: 'eph', label: 'Ê-phê-sô', chapters: 6 },
	{ slug: 'phi', label: 'Phi-líp', chapters: 4 },
	{ slug: 'co', label: 'Cô-lô-se', chapters: 4 },
	{ slug: '1te', label: 'I Tê-sa-lô-ni-ca', chapters: 5 },
	{ slug: '2te', label: 'II Tê-sa-lô-ni-ca', chapters: 3 },
	{ slug: '1ti', label: 'I Ti-mô-thê', chapters: 6 },
	{ slug: '2ti', label: 'II Ti-mô-thê', chapters: 4 },
	{ slug: 'tit', label: 'Tít', chapters: 3 },
	{ slug: 'phil', label: 'Phi-lê-môn', chapters: 1 },
	{ slug: 'he', label: 'Hê-bơ-rơ', chapters: 13 },
	{ slug: 'gia', label: 'Gia-cơ', chapters: 5 },
	{ slug: '1phi', label: 'I Phi-e-rơ', chapters: 5 },
	{ slug: '2phi', label: 'II Phi-e-rơ', chapters: 3 },
	{ slug: '1gi', label: 'I Giăng', chapters: 5 },
	{ slug: '2gi', label: 'II Giăng', chapters: 1 },
	{ slug: '3gi', label: 'III Giăng', chapters: 1 },
	{ slug: 'giu', label: 'Giu-đe', chapters: 1 },
	{ slug: 'kh', label: 'Khải-huyền', chapters: 22 },
];
